### PR TITLE
New registry interface

### PR DESCRIPTION
**Pull request by asim**
DO NOT MERGE

This moves Result to Event and adds a SendEvent method to the registry. We also add a channel for events, switch Action to Type, add Interval and a Message type.

### CODE REVIEW

**Comment by vtolstov** [comment]
Can you switch event type from string to dedicated type , and provide types via const and create String() method for it type?

**Comment by asim** [comment]
We need to think about this. Because every additional event would require modifying the registry to add it. What's your reason for this?

**Comment by vtolstov** [comment]
because if i want to check event type i need to know all strings of events, but in case of "enum" i'm always have all types. Also if i want to store this data or transfer via wire, int types is preferred.
Also this is idiomatic go representation of something that must have concrete value.

**Comment by vtolstov** [comment]
also i don't think that something more like CRUD provides needed for event type.

**Comment by vtolstov** [comment]
Also best to do - NewRegistry returns (Registry, error), and not Registry, but this is needs to modify some other pieces of code too

**Comment by asim** [comment]
That's more related to updating all initialisation related to the cmd package

**Comment by vtolstov** [comment]
@asim, yes. but this is good, we can avoid log.Fatal/log.Fatalf in all registry code

**Comment by asim** [comment]
Ok. Point noted about event type. If we can change initialisation to add error it needs to be everywhere. That's a separate and more painful change.

**Comment by vtolstov** [comment]
yes, i think so (about changing NewRegistry, also this needs to modify all go-plugins registries too)

**Comment by asim** [comment]
Tbh we should be moving cmd into config/cmd and then be changing how plugins are registered

**Comment by vtolstov** [comment]
@asim why?

**Comment by asim** [comment]
I'll PR when I have a complete solution.

**Pull request closed without merging**
