### PR TITLE
fix panic in empty selector, when assign registry

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
close #1189

**Comment by asim** [comment]
not needed. its here https://github.com/micro/go-micro/blob/master/client/options.go#L103

**Comment by vtolstov** [comment]
i'm sure that i saw panic for such stuff, i'm try to reproduce and provide stack trace

**Comment by asim** [comment]
We should not polute options with nil checks. This should be upfront setup. If it fails at this stage there was previously. As initialisation. The reason to not do it here is because we could then just end up doing it in literally every option.

**Comment by vtolstov** [comment]
I found how to i get this issue, this is our standard method for variadic options parsing.
I'm create options struct and fill it.in other places we dont provide new options func. So we need to be consistent

**Comment by asim** [comment]
Where are you creating it? We provide a NewOptions() function that generates a default. We can't cater to empty options being parsed. We have to conform to a single way of how we expect the tools to work. Options functions need to be kept simple. The initialisation should be upfront.

**Comment by vtolstov** [comment]
i think that in flow package i'm utilize NewOptions() and also recheck other usage across go-micro other options structs

**Pull request closed without merging**
