### PR TITLE
return error to caller on grpc server request processing

### PR DESCRIPTION
**Pull request by vtolstov**
returns error from grpc server reqest processing when panic happened

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
relates #898

**Comment by asim** [comment]
Can you do the same for the default server

**Comment by vtolstov** [comment]
@asim you means ServeConn ? it not returns error

**Comment by asim** [comment]
You can write the error back to the client. It's fine I'll sort it out.

**Comment by vtolstov** [comment]
i'm fix the test

**Comment by vtolstov** [comment]
> You can write the error back to the client. It's fine I'll sort it out.

in separate pr ?

**Comment by asim** [comment]
Yea separate PR

**Pull request merged**
