### PR TITLE
api: add static router and improve path parser in rpc handler

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
needs to have some discussion

**Comment by vtolstov** [comment]
i'm add simple test to provide example how to use static router and auto filling proto field based on url path

**Comment by vtolstov** [comment]
in modify own stuff to work with this and it works fine with 5 grpc services behind api with static selector.

**Comment by asim** [comment]
Lets merge and keep iterating!

**Comment by vtolstov** [comment]
cool =) the next step for api is modify protoc-gen-micro  and try to use generated stuff?

**Comment by asim** [comment]
OK, lets try it. I'll let you resurrect the PR or whatever.

**Comment by crazybber** [comment]
It is a very cool stuff

**Pull request merged**
