### PR TITLE
fix Address more then one

### PR DESCRIPTION
**Pull request by 514366607**
when consul Node down
new service can work up.

### CODE REVIEW

**Comment by asim** [comment]
This PR introduces a second call to check the consul agent every time we use the client. Does this not seem excessive?

**Comment by 514366607** [comment]
Only the first time an object is created is it checked , when client is nil。

**Comment by asim** [comment]
How does this solve the problem of something working when the agent is down? Surely you'd have to rotate through the client list on every call to Client() no?

**Comment by 514366607** [comment]
Node consul A   IP : 192.168.0.11
Node consul B   IP : 192.168.0.12
Node consul C   IP : 192.168.0.13

service A
```
re := consul.NewRegistry(
		registry.Addrs("192.168.0.11:8500", "192.168.0.12:8500", "192.168.0.13:8500"),
		consul.TCPCheck(time.Second),
	)
```

When consul Node A goes down
The new service can Register at consul Node B | C

**Comment by 514366607** [comment]
When consul Node A goes down
then leader is consul Node B | C.

If Service A goes down will exit after 1 second(HealthCheck)

**Comment by asim** [comment]
Alright, cool

**Pull request merged**
