### PR TITLE
[fix] ignore unexported field

### PR DESCRIPTION
**Pull request by xpunch**
ignore unexported field when register endpoints

some protobuf unexported field was registered into service endpoints

### CODE REVIEW

**Comment by asim** [comment]
Good fix. I'm gonna need similar in Micro

**Comment by isfk** [comment]
This fix need update golang to 1.17

**Comment by xpunch** [comment]
Thanks for your notice, I'll try to fix that.

**Comment by xpunch** [comment]
@isfk Fixed in #2382.

**Pull request merged**
