### PR TITLE
api/handler: use http.MaxBytesReader and buffer pool

### PR DESCRIPTION
**Pull request by vtolstov**
protect api handlers from OOM cases

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
in next commit i want to add bpool to all usage of iotuil.ReadAll

**Comment by vtolstov** [comment]
i think that this good now. if you have enabled some tracer or monitoring that says api payload size (or count of all api requests in some time and incoming traffic for this time) we can calculate best values for buffer pool (size of preallocated buffer and it count)

**Comment by asim** [comment]
Maybe it makes sense to define the pool somewhere in util or in a shared place so it's just defined once and reused?

**Comment by vtolstov** [comment]
> Maybe it makes sense to define the pool somewhere in util or in a shared place so it's just defined once and reused?

i think about it, but why i duplicate - because some messages for specific handlers may have smaller requirements and some bigger. 
What you think?

**Comment by asim** [comment]
Let's leave as is for now. Whats the current max message size for net/http? You've limited this to 4mb which might pose some issues.

**Comment by vtolstov** [comment]
i'm limit to 10 (fix wrong comment =))
go std lib not limit message body. it limits reading from it in parse form function in request. to 10Mb ib user not uses MaxBytesReader.
So 10Mb is the safe default. also for api i don't think that somembody hits this limit.
If you want to post files bigger - use websocket or raise limit.

**Comment by asim** [comment]
I'm not sure I trust this artificial limit of 10mb. We've now introduced something that potentially breaks existing behaviour for anyone using the API. What if people are throwing a 100mb file upload at it?

**Comment by vtolstov** [comment]
This is api stuff. If you want to upload 100mb go ahead and raise limit.
Also note, that for for large file upload most suitable to use websocket. It allows to resume download and do other cool things

**Comment by asim** [comment]
What I'm saying is its a breaking behaviour for an existing tool. There are 1500+ deployments of the api gateway, you have no idea what people are doing. So to limit it wihtout that knowledge is wrong.

**Comment by vtolstov** [comment]
Do you have some stats data? If not, do you plan to have ability to
gathering some anonymous stats?

чт, 26 мар. 2020 г., 19:56 Asim Aslam <notifications@github.com>:

**Comment by vtolstov** [comment]
For limit, what you want to specify by default, or use 0 as no limit?

**Comment by asim** [comment]
I've set max size to 100mb. Lets see what happens.

**Pull request merged**
