### PR TITLE
continue fix pre version go get bug that unknown v3.5.1

### PR DESCRIPTION
**Pull request by iGoogle-ink**
continue fix pre version go get bug that unknown v3.5.1

### CODE REVIEW

**Comment by iGoogle-ink** [comment]
fix: go get some plugins, report unknow v3.5.1 bug

`~/workspace/jerry/gopher(main*) » go get github.com/asim/go-micro/plugins/server/grpc/v3                                                                          jerry@mac
go: downloading github.com/asim/go-micro/plugins/server/grpc/v3 v3.0.0-20210630062103-c13bb07171bc
go get: github.com/asim/go-micro/plugins/server/grpc/v3@none updating to
        github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210630062103-c13bb07171bc requires
        github.com/asim/go-micro/plugins/client/grpc/v3@v3.0.0-20210629124054-4929a7c16ecc requires
        github.com/asim/go-micro/plugins/registry/memory/v3@v3.5.1: reading github.com/asim/go-micro/plugins/registry/memory/plugins/registry/memory/go.mod at revision plugins/registry/memory/v3.5.1: unknown revision plugins/registry/memory/v3.5.1`

**Comment by iGoogle-ink** [comment]
hello , @asim
The plugins is in the same repo, it is a bit troublesome to repair, you can only use the commit version number of the previous version

**Comment by asim** [comment]
Plugins used to be in their own separate repo but out of interest of keeping things in one place I merged. We've gone through a number of iterations where we had one go mod file then split into two and then per project. It's not clear to me what the right approach is.

**Comment by freezlite** [comment]
Don't you think that plugins should use connonical version instead of pseudo ?

**Pull request merged**
