### PR TITLE
refactor: transport injection

### PR DESCRIPTION
**Pull request by Super-zhw**
Refactor transport injection

1. Redefine the method name
2. Optimize the injection method

### CODE REVIEW

**Comment by Davincible** [comment]
Thanks for the PR. This PR however introduces multiple breaking API changes, which for backward compatibility reasons are not preferred. 

What is the problem exactly with the current behavior?

**Comment by Super-zhw** [comment]
I'm very sorry for ignoring the naming rigor issue due to the PR I merged earlier.
As a result, when using it, the naming was found to be unreasonable, so a correction was proposed.

**Comment by Super-zhw** [comment]
@Davincible
Hello, may I ask if this PR can be incorporated?

**Comment by Davincible** [comment]
There are still breaking API changes

**Comment by Davincible** [comment]
We can make any non breaking changes now, breaking changes will be taken into v5

**Comment by Super-zhw** [comment]
ok thanks

**Comment by Davincible** [comment]
@Super-zhw  Sorry for not being any help now, I'd like to not make breaking changes in minor version upgrades.

If there is any other way to make your life with micro easier please let me know :)

**Pull request closed without merging**
