### PR TITLE
pass additional context for broker subscribe

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
fixes #1103

**Comment by vtolstov** [comment]
@asim don't merge this please, before @amrnt confirms

**Comment by amrnt** [comment]
@vtolstov @asim Tested. It works as expected.

**Comment by asim** [comment]
Merged

**Pull request merged**
