### PR TITLE
feat(util/pool): new pool limit maxIdleConns and maxConns

### PR DESCRIPTION
**Pull request by j2gg0s**
Link issue #2314 

I'm trying to add new pool suport maxIdleConns and maxConns, like golang's http/1 transport.

As a newbie of go-micro, I hope to gather some opinions before I actually done it.

### CODE REVIEW

**Comment by asim** [comment]
@xpunch review?

**Comment by xpunch** [comment]
OK, I'll take a look.

**Comment by xpunch** [comment]
I'm not sure whether a connection pool should provide limitation for max concurrent connection, the use of connection pools is primarily to avoid the cost of setting up new connections all the time, so the intention is to re-use them as frequently as possible.
BTW, the unit tests failed and there is no examples demonstrate how the limit pool works and what scenario it can handle.

**Comment by asim** [comment]
It's not clear to me who's going to maintain this code and with the build not passing and no response in 9 days I'm basically going to say it won't get merged. What's more appropriate is probably if we just accept that client.Pool can be swapped out. So we'll work towards that instead.

**Pull request closed without merging**
