### PR TITLE
RoundRobin strategy

### PR DESCRIPTION
**Pull request by qAison**
No need to start from the first.

### CODE REVIEW

**Comment by asim** [comment]
What's the reason for this change?

**Comment by qAison** [comment]
``` go
services = { s1, s2, s3, s4 }
next := RoundRobin(services)
```

For example, there are 1000 different client first call, the first will be selected s1.
We can provide a random order list when initializing, to avoid the first hit the same focus on the server.

**Comment by asim** [comment]
While the RoundRobin function should likely start with a different index each time, shuffling the nodes is not ideal, that's what a completely random function is useful for. Also not really a fan of the superficial change to the random function. Thanks for the change but I'll likely just set "i" to be a random integer.

**Comment by qAison** [comment]
Yes, that would be simpler.

**Pull request closed without merging**
