### PR TITLE
fixes for safe conversation and avoid panics

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
may be incomplete, but mostly do all needed checks

**Comment by vtolstov** [comment]
@asim what you think about usage of sync/atomic incase of sync.Once ?
if no objection - i can merge it?

**Comment by asim** [comment]
My only issue with atomic is code simplicity and clarity. It adds complexity because it's not something developers use on a day to day basis. So wherever you're making these changes know that you're becoming the maintainer.

**Comment by vtolstov** [comment]
No problem. for me atomic is simpler then create channel to return error.

**Pull request merged**
