### PR TITLE
add set cmd description option

### PR DESCRIPTION
**Pull request by qAison**

### CODE REVIEW

**Comment by asim** [comment]
cmd.Init triggers command line parsing. I'm sorry this cannot be supported in an Option.

**Comment by qAison** [comment]
@asim Can be achieved in other ways?

**Comment by asim** [comment]
https://github.com/micro/go-micro/blob/master/cmd/cmd.go#L204

You can set internal cmd.App.Usage.

**Comment by qAison** [comment]
@asim Micro.NewService After initializing the instance, unable to update settings cmd.app.Usage.

**Comment by asim** [comment]
```
command := cmd.NewCmd()
command.App.Usage = "whatever"

service := micro.NewService(
  micro.Cmd(command),
)
```

or

```
service := micro.NewService()
service.Options().Cmd.App.Usage = "whatever"
```

**Comment by qAison** [comment]
@asim service.Options() is struct, non-pointer,so it can not be updated.

**Comment by asim** [comment]
Then pass in your own command as shown.

**Comment by qAison** [comment]
@asim Thank you for your enthusiastic response, you are the best!(_^__^_)

**Pull request closed without merging**
