### PR TITLE
fix http_broker bug port "0"

### PR DESCRIPTION
**Pull request by printfcoder**
fix the bug 'missing service port'. this bug occurs on we don't set the broker port.

### CODE REVIEW

**Comment by asim** [comment]
This is not the correct fix. If port is 0 it means Connect() was not called and the server has not yet assigned a port. This will basically subscribe the http broker using a completely random port which means unless the server is going to listen on the identical port or the expectation is that this is indirectly subscribing for something else it will not work. 

Can you explain what you're trying to fix and what the existing usage is and why Connect() is not being called before subscribe? If this is a bug related to some other part of the code we should fix that.

**Comment by printfcoder** [comment]
just want to use Broker before calling service.Run():

```
	service := micro.NewService(
		micro.Name("go.micro.config"),
	)
	service.Init(func(options *micro.Options) {
		// ...
		domain.Init(service.Options().Broker)
		// ...
	})

	if err := service.Run(); err != nil {
		panic(err)
	}
```

```
ERRO[0000] [sub] broker sub err: missing service port    source="broker.go:50"
panic: [sub] broker sub err: missing service port
```

**Comment by printfcoder** [comment]
I know I can use  like this:

```
	service.Init(func(options *micro.Options) {
		config.Init()
		options.Broker.Init()
		options.Broker.Connect()
		domain.Init(options.Broker)
		facade.Init(service.Server())
	})
```

but this is not a graceful way.

**Comment by vtolstov** [comment]
If you need to use broker before run service call Connect and use it, what the problem?

**Comment by printfcoder** [comment]
OK. trying another way.

**Pull request closed without merging**
