### PR TITLE
[feature] add publish wrapper

### PR DESCRIPTION
**Pull request by xpunch**
add publish wrapper for client

### CODE REVIEW

**Comment by asim** [comment]
Don't do that. We have a Client wrapper, anyone can wrap the client and define a Publish method.

**Comment by asim** [comment]
The only reason a Call wrapper existed was for convenience but if we have wrappers for all methods its messy. Wrappers should likely be an external construct, not one baked into the client.

**Comment by xpunch** [comment]
I've try the client wrapper, it will create client.Call trace span, which makes jaeger think the service dependent on itself.
Be like:
a.srv /abc
     - a.srv b.srv.Service.Call
     - b.srv b.srv.Service.Call

**Comment by asim** [comment]
It's entirely dependent on how you use it. If you're just publishing you don't implement the Call method, you just return the original client Call. If there is a current client wrapper that doesn't work, it just needs fixing but otherwise it's a better alternative than having a specific publish wrapper, this just makes the client messy and as you can see every client implementation has to do it.

My advice, create a wrapper package or put something in util/wrapper and just wrap the client.

**Comment by JeffreyBool** [comment]
Is it going to be a link trace for mq? It could be based on micro's default wrapper and handler? But is it possible to remove the default trace wrapper? It feels like a lot of the configuration is mandatory

**Pull request closed without merging**
