### PR TITLE
refactored deprecated grpc and removed redundant for loop

### PR DESCRIPTION
**Pull request by tegk**
This is a PR to discuss changes regarding deprecated gRPC methods and removal of a redundant for loop.

Happy to change things :-)

### CODE REVIEW

**Comment by tegk** [comment]
Test passes locally so its rather a Travis issue?

```
2019-11-12 09:39:40.224422 I | Transport [http] Listening on [::]:40419
2019-11-12 09:39:40.224460 I | Broker [http] Connected to [::]:35819
2019-11-12 09:39:40.224709 I | Registry [memory] Registering node: test.function-f09afe10-4e7e-484c-a1c4-c15c11539ab0
2019-11-12 09:39:40.225786 I | Registry [memory] Deregistering node: test.function-f09afe10-4e7e-484c-a1c4-c15c11539ab0
PASS
ok  	github.com/micro/go-micro	0.007s

```

**Comment by asim** [comment]
```
client/grpc/grpc_pool_test.go:33:60: cannot use grpc.WithInsecure() (type grpc.DialOption) as type client.CallOptions in argument to p.getConn
```

Test fails here

**Comment by tegk** [comment]
Will resolve this evening, thanks for the hint :-)

**Comment by asim** [comment]
Tracking chat in #development. Removing the for loop removes the ability for us to do connection pooling. What was the reason for this?

**Pull request closed without merging**
