### PR TITLE
adds Panic & Panicf to logger

### PR DESCRIPTION
**Pull request by gggwvg**

### CODE REVIEW

**Review by vtolstov — APPROVED** [review]

**Comment by vtolstov** [comment]
thanks!

**Comment by asim** [comment]
Why add panic when we have Fatal?

**Comment by vtolstov** [comment]
@asim, because we have panic log level. dont know why we have such level. may be we miss in review?

**Comment by vtolstov** [comment]
best of all - delete panic level and helper

**Comment by gggwvg** [comment]
Fatal means program have to exit.
Panic logs a message than panic.

**Comment by vtolstov** [comment]
this is bad thing, because panic not goes to logger, so this is not good. for panic we need to something like wrapper, that internally have recover() format message, write to output and exit

**Comment by asim** [comment]
yea, as a framework I'm not sure its right to allow people to panic without having recovery

**Comment by vtolstov** [comment]
@asim so to not have two levels with the same stuff, we remove panic?

**Comment by asim** [comment]
Lets remove Panic. I don't think its right for us to promote panicking right now. This is not what we want. I think this is not a practice we want. We want people to return errors where it makes sense because this is microservices, you want to send the error back to the caller.

**Pull request merged**
