### PR TITLE
Added jsonpb rpc codec (stub?)

### PR DESCRIPTION
**Pull request by tudurom**
I think that I nailed the jsonpb codec but I don't know how to test if it actually works.

Might be useful for #218

### CODE REVIEW

**Comment by asim** [comment]
Can you find a way to test this please. You will have to set the content-type on the request to make use of the codec or set it as the default.

**Comment by asim** [comment]
It's also likely better put into go-plugins

**Comment by asim** [comment]
Can you please move this to go-plugins

**Comment by tudurom** [comment]
Will move tomorrow

**Comment by asim** [comment]
Cheers. Closing this then.

**Comment by liilac** [comment]
Seeing as there hasn't been a PR made to go-plugins, I'm working on one at the moment

**Pull request closed without merging**
