### PR TITLE
close r/w

### PR DESCRIPTION
**Pull request by sadwxqezc**
Close writer&reader

### CODE REVIEW

**Review by asim — APPROVED** [review]

**Comment by vtolstov** [comment]
@asim @sadwxqezc if you interesting in mdns registry i think that https://github.com/micro/go-micro/pull/1810/files#diff-2da2b18e238cfc41d240e444a3c1d651R86 needs 
```
defer func () {
  if err := w.Close(); err != nil {
    logger.Errorf("[mdns] registry error: %v", err)
  }
}()

**Comment by sadwxqezc** [comment]
> @asim @sadwxqezc if you interesting in mdns registry i think that https://github.com/micro/go-micro/pull/1810/files#diff-2da2b18e238cfc41d240e444a3c1d651R86 needs
> 
> ```
> defer func () {
>   if err := w.Close(); err != nil {
>     logger.Errorf("[mdns] registry error: %v", err)
>   }
> }()
> ```

Actually you can't use `defer` here，as this part of code needs to call `close` to trigger `flush`。However, logging the error would be perfect

**Comment by vtolstov** [comment]
this is not problem, you can add flush before close

**Comment by sadwxqezc** [comment]
I will open another pr

**Pull request merged**
