### PR TITLE
fix :no syscall.Kill on windows

### PR DESCRIPTION
**Pull request by crazybber**
no syscall.Kill on windows , use os.FindProcess() and process Kill.

### CODE REVIEW

**Comment by crazybber** [comment]
it looks  following code no working.

``` go
	p, err := os.FindProcess(os.Getpid())
	if err == nil {
		p.Kill()
	}
```
but  `syscall.Kill ` still show compiler error, on windows.

**Review by jakexks — APPROVED** [review]

**Comment by vtolstov** [comment]
"This branch is out-of-date with the base branch" may be you need pull go-micro master and merge it to this branch?

**Comment by crazybber** [comment]
> "This branch is out-of-date with the base branch" may be you need pull go-micro master and merge it to this branch?


comments also updated with merge

**Comment by crazybber** [comment]
re-write PR ,based on latest master, to clean PR, also with comments updated .

**Pull request merged**
