### PR TITLE
fix a data race in mdns registry

### PR DESCRIPTION
**Pull request by igorrius**
This commit is suggestion to fix a data race in the `mdns_registry.go` file.

### CODE REVIEW

**Comment by asim** [comment]
Can you provide the stack trace for the race condition please

**Comment by igorrius** [comment]
First of one trace below. If you need a more data, please ping me again.

```
==================
WARNING: DATA RACE
Read at 0x00c000148b40 by main goroutine:
  runtime.mapiterinit()
      /usr/local/go1.11.5.linux-amd64/src/runtime/map.go:734 +0x0
  github.com/micro/go-micro/registry.(*mdnsRegistry).GetService()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/registry/mdns_registry.go:259 +0x36a
  github.com/micro/go-rcache.(*cache).get.func1()
      /home/igorrius/go/pkg/mod/github.com/micro/go-rcache@v0.1.0/rcache.go:117 +0x82
  github.com/micro/go-rcache.(*cache).get()
      /home/igorrius/go/pkg/mod/github.com/micro/go-rcache@v0.1.0/rcache.go:132 +0x237
  github.com/micro/go-rcache.(*cache).GetService()
      /home/igorrius/go/pkg/mod/github.com/micro/go-rcache@v0.1.0/rcache.go:348 +0x5f
  github.com/micro/go-micro/broker.(*httpBroker).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/broker/http_broker.go:526 +0x486
  github.com/micro/go-micro/client.(*rpcClient).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/client/rpc_client.go:513 +0x8e3
  github.com/micro/go-micro.(*clientWrapper).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/wrapper.go:42 +0xe8
  github.com/micro/go-micro.(*publisher).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/publisher.go:15 +0x12b
  main.main()

Previous write at 0x00c000148b40 by goroutine 12:
  runtime.mapassign_faststr()
      /usr/local/go1.11.5.linux-amd64/src/runtime/map_faststr.go:190 +0x0
  github.com/micro/go-micro/registry.(*mdnsRegistry).GetService.func1()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/registry/mdns_registry.go:245 +0x71f

Goroutine 12 (running) created at:
  github.com/micro/go-micro/registry.(*mdnsRegistry).GetService()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/registry/mdns_registry.go:207 +0x300
  github.com/micro/go-rcache.(*cache).get.func1()
      /home/igorrius/go/pkg/mod/github.com/micro/go-rcache@v0.1.0/rcache.go:117 +0x82
  github.com/micro/go-rcache.(*cache).get()
      /home/igorrius/go/pkg/mod/github.com/micro/go-rcache@v0.1.0/rcache.go:132 +0x237
  github.com/micro/go-rcache.(*cache).GetService()
      /home/igorrius/go/pkg/mod/github.com/micro/go-rcache@v0.1.0/rcache.go:348 +0x5f
  github.com/micro/go-micro/broker.(*httpBroker).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/broker/http_broker.go:526 +0x486
  github.com/micro/go-micro/client.(*rpcClient).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/client/rpc_client.go:513 +0x8e3
  github.com/micro/go-micro.(*clientWrapper).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/wrapper.go:42 +0xe8
  github.com/micro/go-micro.(*publisher).Publish()
      /home/igorrius/go/pkg/mod/github.com/micro/go-micro@v0.24.0/publisher.go:15 +0x12b
```

**Comment by igorrius** [comment]
I'm using PubSub scheme.

**Comment by asim** [comment]
So it turns out mdns issues a broadcast query and waits for a specific timeout period before returning. This code https://github.com/micro/go-micro/commit/88e12347d0a08167b0160dfbb52b326e571a2511 now does the same. It waits till the context is done and then returns. It removes the race condition without relying on the mutex.

**Pull request closed without merging**
