### PR TITLE
Preallocate slices in registry.Copy() to avoid append() reallocations when copying data

### PR DESCRIPTION
**Pull request by milosgajdos**
[Partially] addresses #586

### CODE REVIEW

**Review by vtolstov — APPROVED** [review]
looks good, changes are trivial but very useful.

**Comment by vtolstov** [comment]
@milosgajdos83 can you change also https://github.com/micro/go-micro/blob/master/registry/util.go#L7 ?

**Comment by milosgajdos** [comment]
Yep, happy to @vtolstov.  

I'm thinking...we might as well make the same prealloc change across the whole `util.go` file. The initial PR fix was a quick early-morning 😴fix addressing only the `Copy()` function.

**Review by vtolstov — APPROVED** [review]

**Comment by vtolstov** [comment]
thanks, @asim can you merge it?

**Pull request merged**
