### PR TITLE
remove ignore error in method publish

### PR DESCRIPTION
**Pull request by wudi**
Export registry error in method publish.

Show error while service name not found or registry occur some exceptions.

### CODE REVIEW

**Comment by asim** [comment]
The reason we don't do this is because pubsub is mostly an async thing. Subscribers may not exist before a publisher starts sending messages. Whats the reason for returning the error?

**Comment by crazybber** [comment]
need an explain @wudi

**Comment by wudi** [comment]
I think any ready task occur error should export before async.
Just like Marshal error. https://github.com/micro/go-micro/blob/master/broker/http_broker.go#L525

**Comment by asim** [comment]
Considering we're going to move away from http broker, I'm going to merge and lets see what happens.

**Pull request merged**
