### PR TITLE
cache add redis

### PR DESCRIPTION
**Pull request by fengpf**
i find cache only memcache&memory, so i add redis, thanks.

### CODE REVIEW

**Review by fengpf — COMMENTED** [review]
why it not merged

**Comment by asim** [comment]
Please PR in go-plugins

**Comment by fengpf** [comment]
@asim I find in go-plugins no cache dir,  so what can i do?

**Comment by asim** [comment]
Create a cache dir in go-plugins. Memcache will also move there.

**Comment by fengpf** [comment]
ok,thanks

**Pull request closed without merging**
