### PR TITLE
Moving to gRPC by default

### PR DESCRIPTION
**Pull request by asim**
Taking the steps to move to gRPC by default.

Was working on a way to do it cleanly but for now we'll replace the default implementations of the client and server. The full implementation will come soon.

### CODE REVIEW

**Comment by wudi** [comment]
@asim  Why make the gRPC default directly?
Is there have same roadmap ?

**Comment by asim** [comment]
Because everyone wants grpc by default. This PR did not yet enable it.

**Comment by Felyne** [comment]
good.

**Comment by weisd** [comment]
good

**Comment by xmlking** [comment]
Thanks

**Pull request merged**
