### PR TITLE
PatchContext method added

### PR DESCRIPTION
**Pull request by xmlking**
adding PatchContext - this will create new context with original + patch metadata

### CODE REVIEW

**Comment by asim** [comment]
Was this not going to be called Append?

**Comment by xmlking** [comment]
I can change the name, but since `append` name may miss-lead  some users thinking , it only  add given metadata, it actually will overwrite existing metadata if same keys exist. So I thought `patch` will be appropriate name. Let me know if you prefer **append**

**Comment by asim** [comment]
Update then would be better? Patch does not sound right for this context

**Comment by xmlking** [comment]
would you like me add overwrite argument ? 
`AppendContext(ctx context.Context, patchMd Metadata, overwrite bool) ` 

`overwrite defaults to false`

**Pull request merged**
