### PR TITLE
 fix file watcher event bug on Linux

### PR DESCRIPTION
**Pull request by printfcoder**
On Linux(ubuntu, centos), file watcher can only get the file change event twice.

can be tested with this [example](https://github.com/micro/examples/tree/master/config/grpc)

### CODE REVIEW

**Comment by asim** [comment]
Is this only limited to linux? It feels like the change should be applied more broadly.

**Comment by printfcoder** [comment]
@asim yes, I just added a Linux case comment `// + build Linux`, and then other operating systems use `// +build !Linux` which just like before.

**Comment by asim** [comment]
Can you please keep the same structure of the code, we should have watcher.go and watcher_linux.go

**Comment by printfcoder** [comment]
@asim done. please have a check

**Comment by asim** [comment]
Looks good. Can you now squash the commit please.

**Pull request closed without merging**
