### PR TITLE
export registry util function to safe copy registry data

### PR DESCRIPTION
**Pull request by vtolstov**
this functions is duplicated in many registries

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by asim** [comment]
I get the need to reuse it but it's really ugly under registry package as util. It should either be in cache or memory as exported methods.

**Comment by vtolstov** [comment]
why in cache? for example gossip and mdns and memory registry need this functions (may be other registries in plugins too)

**Comment by vtolstov** [comment]
firstly i think about export this function under top level registry package. what you say?

**Comment by vtolstov** [comment]
i'm minimize count of exported func, only Del,Add and Copy.
also fix the issue when adding multiple versions of the same service

**Comment by vtolstov** [comment]
@asim can you merge it?

**Comment by asim** [comment]
I need to review it first

**Comment by vtolstov** [comment]
no problem

**Pull request merged**
