### PR TITLE
simple multicast registry

### PR DESCRIPTION
**Pull request by vtolstov**

### CODE REVIEW

**Comment by asim** [comment]
I don't think this is what we need. We want to optimise mdns. We still want to use a standard to discovery.

**Comment by vtolstov** [comment]
Why you want mdns?what benefits do you have with it?With plain multicast we
can avoid double encoding, and have very simple registry that uses all
other core micro stuff

сб, 18 апр. 2020 г., 11:43 Asim Aslam <notifications@github.com>:

**Comment by asim** [comment]
Because I want to operate on standards as opposed to ad hoc custom things. What I learned from my client/server experience is that inevitably standards win out. And in the case of local discovery mdns is a staple. So I only want to optimise. I also see further long term benefits to it.

**Comment by vtolstov** [comment]
ok,

**Pull request closed without merging**
