### PR TITLE
fix: update dependency certmagic

### PR DESCRIPTION
**Pull request by x1nchen**
module github.com/mholt/certmagic has been renamed github.com/caddyserver/certmagic,
so upgrade on this module will fail.

fix: https://github.com/micro/micro/issues/835

### CODE REVIEW

**Comment by asim** [comment]
Certmagic is used in multiple places. Please update everywhere if providing a fix.

**Comment by x1nchen** [comment]
I'am sorry but I have searched the multiple repo,

https://github.com/micro/go-micro
https://github.com/micro/micro

there is no other place which used `github.com/mholt/certmagic`

**Comment by asim** [comment]
Sorry, I misread, thought this was the micro/micro repo.

**Comment by x1nchen** [comment]
It seem to be cannot merged into master due to failed test.

**Comment by asim** [comment]
It is related to your change.

```##[error]../../../go/pkg/mod/github.com/caddyserver/certmagic@v0.10.13/handshake.go:201:18: hello.SupportsCertificate undefined (type *tls.ClientHelloInfo has no field or method SupportsCertificate)```

Please look at build output

**Comment by x1nchen** [comment]
The field `*tls.ClientHelloInfo.SupportsCertificate` added in go1.14, but CI test runs on go1.13, so it fails.  

I‘am trying to deal with this problem without upgraing go version in CI

**Comment by x1nchen** [comment]
I close this PR and reopen a new tidy one.

**Pull request closed without merging**
