### PR TITLE
feat(api): add extra form content type and extract endpoints from path

### PR DESCRIPTION
**Pull request by leoujz**
api gateway:
- handing http request adds Content-Type application/x-www-form-urlencoded support
- extract endpoints from path if no endpoint matched, only in api case

### CODE REVIEW

**Review by xpunch — APPROVED** [review]

**Comment by Davincible** [comment]
Nice!

Could you explain a bit how the endpoint extraction works?

If I'm not mistaken it now limits you to only have one slash in your URL for your method

**Comment by leoujz** [comment]
The original code use rsp.Method as the endpoint name. As the strategy mentioned in https://github.com/go-micro/api, I extract the endpoint name from rsp.Path. If any endpoint matched before this code, this would never happen, this only runs when no endpoint mathced, as a final default value. when using rsp.Method, like POST, GET, would never work.

**Comment by leoujz** [comment]
And 3 failing checks relative to my code? I don't know how to fix that

**Comment by Davincible** [comment]
Makes sense, thanks for the PR!

Checks are not relative to your change.

**Pull request merged**
