### PR TITLE
Fix cache-selector concurrency problem of locked time too long 

### PR DESCRIPTION
**Pull request by jichre**
When i ab-test my program, found the blocked time was so long at selector/cache:get.
So i changed the mutex type to rwmutex, and fetch from registry async.

### CODE REVIEW

**Comment by asim** [comment]
So the cache miss is only on first request right, so thats slow and the rest fast? Is this optimisation necessary?

**Comment by jichre** [comment]
I changed go-rcache the same first, test commad :
ab -n 100000 -c 1000 "my gateway url"
qps will add 5-10%
I used "go tool trace" to analysis find this 
fb6b3a85-3f9b-46dd-9b9f-3f102ebce7a8

**Comment by asim** [comment]
Interesting. I can see the value but the implementation needs work. I think we can likely move to RWMutex without the need for the async call. First cache miss would be a slow call going to the registry but everything else would be fast.

**Comment by jichre** [comment]
OK!
Hope for better

**Comment by asim** [comment]
Please test this https://github.com/micro/go-micro/pull/352

**Comment by asim** [comment]
Merged the fix as release 0.15.1

**Pull request closed without merging**
