### PR TITLE
RPC stream client/server mutex fix

### PR DESCRIPTION
**Pull request by veger**
As described in #878 (and #532) it is not possible to send messages while waiting to receive them as well (or vice-versa), due to RPC stream client and server being locked by both `Send()` and `Recv()` functions.

In order to solve this issue, I unlock the Mutex before calling the `codec` to receive data, and locking it again after `codec` returned.
This way we still have the Mutex protection of the client/server structs, but we can send/receive at same time.

:warning: Note that this assumes that `codec` does not need protection while being active.

I did not update `Send()` because I assumed that it won't block. By only fixing `Recv()` the `Send()` worked as welll. Maybe depending on transport/codec it can block as well?

I only considered these 2 components/files, as we are (currently) not having issues in other parts of the go-micro framework regarding to this. If needed I can update other parts as well to stay in sync with this change.

I have tested this in our micro-service environment and it all seems to work fine. I did not trigger race conditions or other panics. But I did not yet perform (high) load or long running tests, which would make race conditions more likely to pop up (if there are any).

### CODE REVIEW

**Comment by asim** [comment]
We'll need a test to validate this continues to work as expected without race conditions and continues to send and receive messages in the right sequence. We also want to see this tested in parallel and under load.

**Comment by veger** [comment]
Do you have a proposal how to test this?
Only codec and extractor have some tests, server/client code is fully untested at the moment... (as far as I can see)

**Comment by veger** [comment]
We are using this fix for quite a while already, and it seems to be working nicely in our cloud environments.

In addition we found a race condition in the `Close()` function:
```
	select {
	case <-r.closed:
		return nil
	default:
		close(r.closed)
```

There is a small gap were 2 go routines can call Close() and the channel is not yet closed, resulting in a panic that `r.closed` is closed twice...
The latest commit adds the Mutex to the `Close()` function as well to protect against this.

**Comment by vtolstov** [comment]
if the question about how to test i tink that it will be easy:
write test that spawns two micro services that ping/pong messages and run it with go test -race flag
to check race conditions i thing that we need some concurrency like 100-1000 connections between of them.
I think that it is enough to test this changes.
Also i'm try to switch own stack to use grpc service and transport and check it too.

**Comment by asim** [comment]
We can't accept this without actual tests which account for any race conditions in codec but also sequencing of requests. Removing the locking exposes an issue that can lead to such a problem. Its not enough to send and receive, you have to actually send and receive the messages in order.

**Comment by vtolstov** [comment]
@veger do you have time to write tests and check the code ?

**Comment by veger** [comment]
Not a lot, especially since there are no such tests yet I could base it on (or extend).

But I think I have some time today to figure out how to write them to test the 'race condition in codec' and 'sequence of requests'

**Comment by asim** [comment]
Surely it's just a test use of the server? Start a server and execute an endpoint in parallel?

**Comment by veger** [comment]
**About sequence test**

I wrote a simple Sequence test, but it generally does not make sense, as it write something 1000 and then read it reads it a 1000 times. So of course it is in same order (no concurrency and the whole Mutex is not required)

I could put it in some go routines, but then the order can vary depending on the golang scheduler (on both read and write side).

**About concurrency test**

I spawn 10 go routines to write data 10 times (with some random delay to have better chance to trigger race condition) and 10 go routines to read the data (not checking as I don't care about payload/order now)

No race conditions are detected with current test, but as you can see I switched to proto codec (which we use :wink: ).
The json codec uses a shared encoder/decoder internally which is triggering race conditions (which makes sense).

So the concurrency test shows the change works for the rpc_stream.go, but it trigger race conditions in other place(s).

**Conclusion**

If these kind of tests are what you are looking for, I am willing clean them up, add client/rpc_stream.go tests, include all codecs to the tests, and fix them.
But I rather know before I make these changes, to potentially prevent a lot of work getting thrown away.
If you like to see other/more tests, also let me know.

**Comment by vtolstov** [comment]
thanks!

1) in Send may be good not r.Lock()/defer r.Unlock() from begining?
r.RLock() before r.IsClosed(), r.RUnlock() after setting r.err
r.RUnlock() after 

and so on ?

**Comment by veger** [comment]
You mean for `client/rpc_stream.go#Send()`, as I cannot see the `IsCLosed()` in the `server/rpc_stream.go#Send()`?

**Comment by veger** [comment]
The json codec cannot be fixed properly (to support both read and write as same time), as it has the (shared) `Conn` so it needs to block... Or the (buffered) Decoder/Encoder needs to be replaced with json.(Un)Marshall in order to fully prevent the race condition in this codec

**Comment by veger** [comment]
The grpc codec also has issues: The `ReadHeader()` sets `c.ContentType` and the `ReadBody()` uses it. In between some other call to `ReadHeader()` can be called changing the content type (not very likely in a (proper) application, but it is possible).

To fix this the `ContentType`, needs to be stored in `Message` which needs to be returned to `ReadBody()` so it can (re)use it.

**Comment by veger** [comment]
What is the best course to solve this in your opinions?

I see the following possibilities:
1. Fix all, which will require a lot of internal refactoring/fixing.
2. Create a new/separate 'real async' RPC stream client/server, to be used with limited codecs (the ones without race conditions)
3. Ignore this PR (and maybe add a note that it is not really async in the sense that it is only possible to send _or_ receive and the same time)

For us either option 1 or 2 have our preference (for option 3 it means we need to keep and maintain our fork...), quality-wise I think option 1 would be best... (maybe option 2 can grow into 1 over time?)

Please let me know, so I know how to fix issues for this PR.

**Comment by vtolstov** [comment]
as i understand 2 means that after creating new client/server you add one by one fixed codecs ?

**Comment by veger** [comment]
2 would require codecs that are deemed safe. The ones we fixed and checked for race conditions.
I guess using a (different) `interface` we can enforce this @ compile time?

**Comment by vtolstov** [comment]
@asim what you can say and suggest?

**Comment by asim** [comment]
I think @veger has a specific requirement that no one else has had an issue with yet. I don't really know what the best place is for this considering codecs are not thread safe and were never intended to be. I believe most of this pushes for an internal refactor rather than hacks.

So I'm inclined to say 1. is the best option and for the moment either maintaining your own client/server is probably the best approach until that happens. Remember that go-micro is pluggable and the intention was always for people to adopt the same interfaces but plug and play where necessary.

Ultimately my goal is to have the http transport be the default and defacto transport that operates on http 1.1, http2 and http3 in the future. I'd then like the ability to operate on any protocol in our client and server without having to maintain a separate implementation for grpc and other things. So wherever we can improve I think that makes sense.

Tbh if the codecs did not do any internal mutation it would be simpler but thats hard to get right at the moment.

I can take a look at this issue/code next month during the quiet period over christmas. I have a feeling I'll be able to produced the desired outcome with limited code changes but that might introduce locking in a more fine grained way.

**Comment by vtolstov** [comment]
My own IMHO: We need to say that codecs are not thread safe, so who use it must provide locking.
So in case of go-micro - locking must be set on transport or server/client level. If we have locks inside codecs to i think that we bring up slowdown with mutex contention.

**Comment by asim** [comment]
Well only alternative is to refactor codes to

```
type Codec interface {
    ReadHeader(b []byte) (Header, error)
    ReadBody(b []byte, v interface{}) error
    Write(v interface{}) ([]byte, error)
}
```

Or something like that

**Comment by veger** [comment]
@asim your refactoring will help to be able to make the codecs 'lockable' form the outside yes. As they are now, it is not possible as reading and writing to the connection (and thus blocking) is done inside the codecs. All of them that share their state (buffer) are 'unlockable' from outside.

The protobuf codec is an example that does not share state (that is why I could use it for my test)

I'll wait until I hear from you again, hopefully with some good new, but otherwise I/we can give it another try (with some additional instructions or plans you guys have).

**Comment by asim** [comment]
I am going to merge this code. We are moving to grpc by default which will radically improve performance but having this fix may also be useful where we're using it for transport agnostic services. Obviously there's still a refactor required but I don't have time to deal with that at the moment.

**Pull request merged**
