### PR TITLE
Extract should not include loopback addresses

### PR DESCRIPTION
**Pull request by gggwvg**
Now Extract can get 127.0.0.1, causing the registered address of the service to be 127.0.0.1 and not accessible

### CODE REVIEW

**Comment by gggwvg** [comment]
@asim

**Comment by gggwvg** [comment]
@vtolstov

**Comment by gggwvg** [comment]
image

My service running on k8s, registered as 127.0.0.1 in consul, that is not the real node IP.
My env MICRO_SERVER_ADDRESS=":9090"

https://github.com/micro/go-micro/blob/v2.2.0/server/grpc/grpc.go#L594

In my case, `addr.Extract("")` returns 127.0.0.1, that is not as expected.

**Comment by asim** [comment]
Specify 0.0.0.0 as your address

**Comment by vtolstov** [comment]
Can you provide list of all addresses ?

**Comment by gggwvg** [comment]
> Specify 0.0.0.0 as your address

It's not work.
Although my env MICRO_SERVER_ADDRESS="0.0.0.0:9090", IP in consul is still 127.0.0.1:9090, that's a invalid service address.

image

**Comment by gggwvg** [comment]
> Can you provide list of all addresses ?

image

**Comment by vtolstov** [comment]
Micro try to bind to internal address, so you need to add any internal address

**Pull request closed without merging**
