### PR TITLE
bumped quic-go version to v0.12.1

### LINKED ISSUE #758: quic-go  checksum mismatch ?
any one come across this error when doing `go mod download` ?
I  am seeing this error in docker builds
 
```
verifying github.com/lucas-clemente/quic-go@v0.12.0: checksum mismatch
	downloaded: h1:dYHUyB50gEQlK3KqytmNySzuyzAcaQ3iuI2ZReAfVrE=
	go.sum:     h1:TRbvZ6F++sofeGbh+Z2IIyIOhl8KyGnYuA06g2yrHdI=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

### PR DESCRIPTION
**Pull request by theophanous**
As per [https://github.com/lucas-clemente/quic-go/issues/2163](https://github.com/lucas-clemente/quic-go/issues/2163 ) quic-go has been re-tagged as v0.12.1 to fix checksum mismatch errors

bumped quic-go to v0.12.1, followed by "go mod tidy".

resolves #758

### CODE REVIEW

**Comment by milosgajdos** [comment]
Thanks for the PR, but it looks like it's pulling in a truck loads of unnecessary dependencies?

**Comment by theophanous** [comment]
This is caused by me running **go mod tidy**

I've always run go mod tidy to keep all dependencies in check, happy to update the pull request with just the quic-go version bump if we want to avoid indirect dependencies

<details>
<summary>Dependency details...</summary>

```
> go mod why -m github.com/bmizerany/assert
github.com/micro/go-micro/config/reader/json
github.com/bitly/go-simplejson
github.com/bitly/go-simplejson.test
github.com/bmizerany/assert

> go mod why -m github.com/coreos/bbolt
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/auth
github.com/coreos/etcd/mvcc/backend
github.com/coreos/bbolt

> go mod why -m github.com/coreos/go-semver
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/etcdserver
github.com/coreos/go-semver/semver

> go mod why -m github.com/dgrijalva/jwt-go
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/auth
github.com/dgrijalva/jwt-go

> go mod why -m github.com/go-telegram-bot-api/telegram-bot-api
github.com/micro/go-micro/agent/input/telegram
gopkg.in/telegram-bot-api.v4
gopkg.in/telegram-bot-api.v4.test
github.com/go-telegram-bot-api/telegram-bot-api

> go mod why -m github.com/golang/groupcache
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/proxy/grpcproxy
github.com/coreos/etcd/proxy/grpcproxy/cache
github.com/golang/groupcache/lru

> go mod why -m github.com/grpc-ecosystem/go-grpc-middleware
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/etcdserver/api/v3rpc
github.com/grpc-ecosystem/go-grpc-middleware

> go mod why -m github.com/grpc-ecosystem/go-grpc-prometheus
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/grpc-ecosystem/go-grpc-prometheus

> go mod why -m github.com/grpc-ecosystem/grpc-gateway
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/embed
github.com/grpc-ecosystem/grpc-gateway/runtime

> go mod why -m github.com/hashicorp/memberlist
github.com/micro/go-micro/registry/consul
github.com/hashicorp/consul/api
github.com/hashicorp/consul/api.test
github.com/hashicorp/serf/serf
github.com/hashicorp/memberlist

> go mod why -m github.com/jonboulle/clockwork
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/etcdserver/api/v2http
github.com/jonboulle/clockwork

> go mod why -m github.com/lucas-clemente/quic-go
github.com/micro/go-micro/transport/quic
github.com/lucas-clemente/quic-go

> go mod why -m github.com/nats-io/nats-server/v2
github.com/micro/go-micro/broker/nats
github.com/nats-io/nats.go
github.com/nats-io/nats.go.test
github.com/nats-io/nats-server/v2/server

> go mod why -m github.com/prometheus/client_golang
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/prometheus/client_golang/prometheus/promhttp

> go mod why -m github.com/prometheus/client_model
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/prometheus/client_golang/prometheus/promhttp
github.com/prometheus/client_model/go

> go mod why -m github.com/soheilhy/cmux
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/soheilhy/cmux

> go mod why -m github.com/tmc/grpc-websocket-proxy
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/embed
github.com/tmc/grpc-websocket-proxy/wsproxy

> go mod why -m github.com/xiang90/probing
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/rafthttp
github.com/xiang90/probing

> go mod why -m go.etcd.io/bbolt
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/auth
github.com/coreos/etcd/mvcc/backend
github.com/coreos/bbolt
github.com/coreos/bbolt.test
go.etcd.io/bbolt

> go mod why -m golang.org/x/time
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/proxy/grpcproxy
golang.org/x/time/rate

> go mod why -m gopkg.in/go-playground/assert.v1
github.com/micro/go-micro/api/handler/cloudevents
gopkg.in/go-playground/validator.v9
gopkg.in/go-playground/validator.v9.test
gopkg.in/go-playground/assert.v1

> go mod why -m sigs.k8s.io/yaml
github.com/micro/go-micro/config/source/etcd
github.com/coreos/etcd/clientv3
github.com/coreos/etcd/clientv3.test
github.com/coreos/etcd/integration
github.com/coreos/etcd/embed
sigs.k8s.io/yaml


```
</details>

Looking over them they appear to be test dependencies

**Comment by milosgajdos** [comment]
Well they weren't needed before, so I'm a bit surprised they should be needed now.

`go mod` is a hot pile of mess tbh, so I'm not sure. Tidying deps should mean removing unneeded ones not adding a bunch of indirect deps to main `go.mod` file.  

Frankly I've no idea what `go mod tidy` is supposed to do and how, unfortunately, but I understand the appeal of it :-)

I'm going to leave this for @asim to comment.

**Comment by asim** [comment]
Agree with Milos. Please remove the indirects and only update quic-go

**Pull request merged**
