### PR TITLE
Cloudflare Store implementation for workers KV

### PR DESCRIPTION
**Pull request by jakexks**
As the cloudflare go library doesn't expose expiring keys, this isn't complete yet.

### CODE REVIEW

**Comment by vtolstov** [comment]
I think that pr needs to be for go-plugins repo

**Comment by jakexks** [comment]
Fair comment. It's a PR against go-micro as we are about to use it, and @asim doesn't want to pull go-plugins in the main build. However, it might be good to make everything a plugin and have a selective build.

**Comment by vtolstov** [comment]
This is bad thing. We again bloat go.mod deps for go-micro.

**Comment by asim** [comment]
Can you offer a better solution? We otherwise have to "download the world" by using go-plugins.

**Comment by vtolstov** [comment]
Better split it to logical parts like wrappers store, brokers and so.

**Pull request merged**
