### PR TITLE
implement some gossip options

### PR DESCRIPTION
**Pull request by vtolstov**
* fix panic, when context is nil
* provide Address, Advertise, Config options

Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
don't understand, but found this issue:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xefa89f]

goroutine 1 [running]:
github.com/unistack-org/go-micro/registry/gossip.configure(0xc0001ba8c0, 0xc0001b4038, 0x1, 0x1, 0xc0001a46f0, 0x7f14eec286c0)
        vendor/github.com/unistack-org/go-micro/registry/gossip/gossip.go:112 +0x30f
github.com/unistack-org/go-micro/registry/gossip.NewRegistry(0xc0001b4038, 0x1, 0x1, 0xc0001aa6a0, 0xc0001a46f0)
        vendor/github.com/unistack-org/go-micro/registry/gossip/gossip.go:580 +0x19f
```

**Comment by asim** [comment]
Context is likely nil. It needs to be preset in options. Otherwise looks good. Except please don't change the password.

**Comment by asim** [comment]
Ok thats fine but lets call it something useful like `micro-gossip-key`

**Comment by asim** [comment]
My advice would be to create the context when the options are created in NewRegistry. Likely fixes the panic.

**Comment by vtolstov** [comment]
Ok im change it, im eechek context issue and dont see that it nil.

ср, 19 дек. 2018 г., 6:33 Asim Aslam notifications@github.com:

**Comment by asim** [comment]
Well something is invalid and throwing a nil pointer so something is by definition nil.

**Comment by asim** [comment]
`	if optConfig, ok := g.options.Context.Value(contextConfig{}).(*memberlist.Config); ok && optConfig != nil {
`

This is the line, the only possibility here is either context is nil or the value itself is nil. You should not cast before it's actually checked for availability.

**Pull request merged**
