### PR TITLE
pass micro errors from grpc server to grpc client

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
server/grpc and client/grpc must be fixed to use proto.Message based error

**Comment by asim** [comment]
This is quite clever

**Comment by asim** [comment]
Should we merge?

**Comment by vtolstov** [comment]
I think so. If we have another issues with this, we can fix later

**Pull request merged**
