### PR TITLE
subscriber recovery

### PR DESCRIPTION
**Pull request by vtolstov**
Signed-off-by: Vasiliy Tolstov <v.tolstov@unistack.org>

### CODE REVIEW

**Comment by vtolstov** [comment]
may be fixes https://github.com/micro/go-micro/issues/832

**Comment by asim** [comment]
You do not need a channel for this. An error value can be set in defer before returning.

**Comment by vtolstov** [comment]
@asim does the never commit looks good?

**Comment by asim** [comment]
Yea makes sense

**Pull request merged**
