### PR TITLE
fix: use registry from opts not use default directly:(#1436)

### PR DESCRIPTION
**Pull request by crazybber**
ref to : #1436

### CODE REVIEW

**Comment by asim** [comment]
What if hte registry is nil?

**Comment by crazybber** [comment]
> What if hte registry is nil?

u r right, nil need to be checked .i will fix it.

**Comment by asim** [comment]
The registry is used elsewhere in the code. This is not enough.

**Comment by crazybber** [comment]
yeah ,my careless , fix it in options.

**Comment by crazybber** [comment]
@asim any comments ?

**Comment by vtolstov** [comment]
Thanks, looks good. Minor thing comments to public funcs.

**Comment by vtolstov** [comment]
Can you update branch and fix comments?

**Comment by crazybber** [comment]
> Can you update branch and fix comments?

comments fixed.

**Comment by vtolstov** [comment]
"This branch is out-of-date with the base branch" may be you need to pull go-micro master and merge it to this branch?

**Comment by crazybber** [comment]
> "This branch is out-of-date with the base branch" may be you need to pull go-micro master and merge it to this branch?

comments also updated with merge

**Comment by asim** [comment]
Has anyone tested this works with the existing web usage? Has anyone switched a registry without setting it to see if it works? Because I have previously seen a broken experience. Someone please test and confirm.

**Comment by vtolstov** [comment]
i dont understand how this can broke something.
if user not set registry option all wark as before, if set - use another registry.
mostly we have two unneeded parts 
https://github.com/micro/go-micro/blob/master/web/service.go#L117
https://github.com/micro/go-micro/blob/master/web/service.go#L144

**Comment by asim** [comment]
Specify --registry=etcd and see if the web service registry is actually set.

**Comment by vtolstov** [comment]
cmdline and env parsing doing via micro.NewService, so i think that it not set with this option.
But if you set registry via go, why it can't be set?

**Comment by asim** [comment]
go-micro/web uses config/cmd internally. So I believe if you don't use go-micro/registry/DefaultRegistry then it fails to initialise. Basically no one has tested the backwards compatibility of this PR and its been merged. Please test the usage of the flags and env vars.

**Comment by vtolstov** [comment]
Ok, im test it

**Comment by asim** [comment]
This change broke everything as I mentioned. It was merged untested. Please do not merge untested code that may have adverse effects everywhere. Future PRs will first go through test environment before being merged. Reverting https://github.com/micro/go-micro/pull/1489/files

**Pull request merged**
