### PR TITLE
cleanup go.mod remove replace section

### PR DESCRIPTION
**Pull request by leaxoy**
This PR cleanup go.mod file, remove `replace` and `exclude` section, and work well. This will solve deps hell, I think.

### CODE REVIEW

**Comment by asim** [comment]
Are these manual edits to the modules?

**Comment by leaxoy** [comment]
No， I use `go mod tidy` maintain this file, while go version is 1.12.5

**Comment by leaxoy** [comment]
In fact, first remove `replace` and `exclude`, then run `go mod tidy`

**Comment by asim** [comment]
And if you run go get -u ./...?

**Comment by leaxoy** [comment]
Only `go mod tidy` been run, I try run `go get -u ./...` on my local pc, it success without `replace`, but add new deps to `go.mod`, should I add those deps to this PR?

**Comment by vtolstov** [comment]
Looks good

**Comment by asim** [comment]
Why is it importing grpc-gateway and related things now? There are deps here that seem totally unrelated.

**Comment by vtolstov** [comment]
this is indirect dep, some of used dep uses github.com/grpc-ecosystem/grpc-gateway

**Comment by vtolstov** [comment]
i'm do myself go mod tidy so i'm compare my results with this pr.
i think that this is etcd dep (grpc-gateway)

**Comment by leaxoy** [comment]
Sorry for the delay due to time difference， like @vtolstov  says，  grpc-gateway is an indirect dep， it should be imported by other dep.

**Comment by asim** [comment]
Strangely if I remove the file and do it now I don't even get that dependency

**Comment by vtolstov** [comment]
Strange

пт, 7 июн. 2019 г., 10:05 Asim Aslam <notifications@github.com>:

**Pull request merged**
